### ISSUE TITLE
using webpack 5.70 onBeforeBuild does not run scripts like the other events

### ISSUE THREAD

**Issue by boltex** [s00d/webpack-shell-plugin-next#36]
onBeforeBuild doesnt seem to trigger on my project using webpack 5.70. 

Others like onBuildStart all seem to work

**Comment by enigma1** [comment]
I was getting the same issue till I set the "dev" flag to false Default is true and will patch the scripts array with an empty one due to the defaultTaks settings. I used the watchRun in my case but it's the same for beforeBuild

`      if (this.dev) {
        this.onBeforeBuild = JSON.parse(JSON.stringify(defaultTask))
      }`

`const defaultTask: Tasks = {
  scripts: [],
  blocking: false,
  parallel: false
}`

**Comment by s00d** [comment]
hello. Try 2.3.1

**Comment by enigma1** [comment]
by the way where is the 2.3.1 release? The latest shows as 2.2.2

**Comment by s00d** [comment]
https://www.npmjs.com/package/webpack-shell-plugin-next/v/2.3.1
